# Generated by Django 3.2.13 on 2022-09-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_articles_a'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A',
            new_name='Articles',
        ),
    ]
